# Site settings
title: Parole che crescono
email: annamadonna8@gmail.com
url: https://anna-madonna.github.io/Parole-che-crescono/
description: Laboratorio di lettura dialogica con libri in simboli rivolto ai bambini del nido.
keywords: "lettura dialogica, libri in simboli, CAA, comunicazione aumentativa e alternativa, nido d'infanzia, laboratorio educativo, inclusione, Parole che crescono"
meta_author: Luciano Giuseppe
lang: it
social_image: /img/propic.jpeg

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


collections:
  guide:
    output: true

# Footer settings
#footer:
#  copyright: Giuseppe Luciano
#  location: Italy

author:
  name: Giuseppe Luciano
  email: giuseppe.luciano03@gmail.com

footer:
  copyright: "Giuseppe Luciano"
  location: "Bologna, Italia"
  credits_title: "Contatti"
  name: "Giuseppe Luciano"
  email: "giuseppe.luciano03@gmail.com"
  email:: "https://sigfrido11.github.io/personal_website/"
  github: "https://github.com/sigfrido11"
  
# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
